### ISSUE TITLE
Error on step 7 for backend installation

### ISSUE THREAD

**Issue by psycholyzern** [erindru/openseedbox#11]
Got this error 

```
~  _ __ | | __ _ _  _| |
~ | '_ \| |/ _' | || |_|
~ |  __/|_|\____|\__ (_)
~ |_|            |__/
~
~ play! 1.2.5, http://www.playframework.org
~ framework ID is prod
~
~ OK, /src/openseedbox-server is started
~ output is redirected to /src/openseedbox-server/logs/system.out
~ pid is 10834
~
root@seed-be-1:/src/openseedbox-server# Exception in thread "main" play.exceptions.UnexpectedException: SienaPlugin : not using GAE requires at least a db=xxx config
        at play.modules.siena.SienaPlugin.dbSqlType(SienaPlugin.java:58)
        at play.modules.siena.SienaPlugin.dbType(SienaPlugin.java:88)
        at play.modules.siena.GoogleSqlDBPlugin.onLoad(GoogleSqlDBPlugin.java:63)
        at play.plugins.PluginCollection.initializePlugin(PluginCollection.java:251)
        at play.plugins.PluginCollection.loadPlugins(PluginCollection.java:185)
        at play.Play.init(Play.java:294)
        at play.server.Server.main(Server.java:159)
```

**Comment by psycholyzern** [comment]
I still have my server powered on. I can provide you access if I can pass the details in a safe way. I stopped  at the error mentioned above

**Comment by erindru** [comment]
Can you try adding a line `db=mem` to the openseedbox-server application.conf file?

**Comment by psycholyzern** [comment]
done..errors done.. But, ip:9001 is inaccessable. Do I need to run nginx first? I havent install nginx yet

**Comment by erindru** [comment]
hmm it should be accessible, Play! starts a webserver. what happens if you `curl http://localhost:9001` from the shell of the computer openseedbox-server is running on? Also, check `logs/system.out` for errors

**Comment by psycholyzern** [comment]
curling have grabbed some html codes. Then I refreshed ip:9001 in my browser and it works. But this errors shows up in my console

```
Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/src/openseedbox-common/lib/ttorrent-1.1.4.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/play-1.2.5/framework/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
```

This is my ```system.out```'s log

```
CompilerOracle: exclude jregex/Pretokenizer.next
11:38:23,250 INFO  ~ Starting /src/openseedbox-server
11:38:23,259 INFO  ~ Module openseedbox is available (/src/openseedbox-server/../openseedbox-common)
11:38:23,260 INFO  ~ Module siena is available (/src/openseedbox-server/modules/siena-2.0.7)
11:38:25,229 INFO  ~ Precompiling ...
11:38:54,990 INFO  ~ Connected to jdbc:h2:mem:play;MODE=MYSQL
11:38:55,066 INFO  ~ Siena DB Type: sql:h2:mysql
11:38:55,278 INFO  ~ Application 'openseedbox-server' is now started !
11:38:55,691 INFO  ~ Listening for HTTP on port 9001 ...

```

**Comment by wesleynunes121** [comment]
add this lines in /src/openseedbox-server/application.conf

db.url=jdbc:mysql://localhost/openseedbox
db.driver=com.mysql.jdbc.Driver
db.user=user
db.pass=pass

**Comment by erindru** [comment]
Why? openseedbox-server doesnt talk to a MySQL database, in fact the only reason to add `db=mem` to the config file was to work around a Play! issue

**Comment by wesleynunes121** [comment]
My 9001 only work when I added these lines.

**Comment by psycholyzern** [comment]
Well, my problem solved.
