### ISSUE TITLE
TransmissionBackend.java could not be compiled

### ISSUE THREAD

**Issue by drew442** [erindru/openseedbox#14]
Hi,

I'm getting the following error when I'm starting the backend:

The file /app/com/openseedbox/backend/transmission/TransmissionBackend.java could not be compiled. Error raised is : The method encodeBase64String(byte[]) is undefined for the type Base64

play.exceptions.CompilationException: The method encodeBase64String(byte[]) is undefined for the type Base64
        at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
        at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
        at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
        at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
        at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:426)
        at play.Play.preCompile(Play.java:600)
        at play.Play.init(Play.java:304)
        at play.server.Server.main(Server.java:162)

Are you able to help?

**Comment by erindru** [comment]
What's the output of `java -version` on your system?

**Comment by drew442** [comment]
java version "1.6.0_34"
OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 23.25-b01, mixed mode)

**Comment by drew442** [comment]
I ended up adding commons-codec to the dependencies so that it would download a version that had the encodeBase64String method

Just add the following to the dependencies and run play deps
    - commons-codec -> commons-codec 1.7

**Comment by drew442** [comment]
I forgot to click close with my previous comment.
